name: "Zip Project"
description: "Zips the project for distribution"

runs:
  using: "composite"
  steps:
    - name: Zip
      shell: bash
      run: |
        zip -r deltagreen.zip . \
          -x "packs/source/*" \
          -x "build/*" \
          -x "dist/*" \
          -x ".*" \
          -x "package.json" \
          -x "package-lock.json" \
          -x "node_modules/*" \
          -x "site/*"
